title: Mateusz Buda
description: Machine Learning Engineer and AI Product Developer
author: Mateusz Buda
github_username: mateuszbuda
twitter_username: budamat
email: buda@kth.se
google_analytics: UA-43468306-2
theme: minima
