title: Mateusz Buda
description: Research Scholar in Computer Vision and Machine Learning at Duke University.
author: Mateusz Buda
github_username:  mateuszbuda
twitter_username: budamat
email: buda@kth.se
google_analytics: UA-43468306-2
theme: minima
